apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-github-page
  annotations:
    github.com/project-slug: khngu/khngu.github.io
    backstage.io/techdocs-ref: url:https://github.com/khngu/khngu.github.io
spec:
  type: website
  lifecycle: experimental
  owner: khngu
