site_name: 'My Documentation'
site_description: 'My GitHub Pages Documentation'

nav:
  - Home: index.md

repo_url: https://github.com/khngu/khngu.github.io/tree/main/docs
edit_uri: edit/main/docs/

plugins:
  - techdocs-core

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
    permalink: true
