site_name: 'My Documentation'
site_description: 'My GitHub Pages Documentation'
nav:
  #- Home: index.md
  #- Onboarding: onboarding.md
  #- Team: team.md
  #- Tools: tools/
  #- Getting Started: test/getting-started.md
  #- Test: test/test2/_index.md
  - Home: content/docs/developer_manual/_index.md
repo_url: https://github.com/khngu/khngu.github.io/tree/main/website
edit_uri: edit/main/website
plugins:
  - techdocs-core
  - search
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - extra.css
extra_javascript:
  - extra.js
theme:
  name: material
  palette:
    #- scheme: default
    #  primary: red
    #  accent: red
    #- scheme: slate
    #  primary: indigo
    #  accent: indigo
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
