site_name: 'Developer Manual'
site_description: 'Developer Documentation'
docs_dir: website/content/docs/developer_manual
nav:
  - Home: index.md
  - Getting Started: getting_started/
  - Infrastructure: infrastructure/
  - Kubernetes: kubernetes/
  - O11y: o11y/
  - Technical Solutions: technical_solutions/
  - Toolchain: toolchain/
  - Tutorials: tutorials/
repo_url: https://github.com/khngu/khngu.github.io/tree/main/website/content/docs/developer_manual
edit_uri: edit/main/website/content/docs/developer_manual
plugins:
  - techdocs-core
  - search
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - extra.css
extra_javascript:
  - extra.js
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
