site_name: 'My Documentation'
site_description: 'My GitHub Pages Documentation'

nav:
  - Home: index.md
  - About: about.md

plugins:
  - techdocs-core

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
