site_name: 'My Documentation'
site_description: 'My GitHub Pages Documentation'
docs_dir: 'website/content/docs/developer_manual'
nav:
  - Home: _index.md
  - Getting Started: getting_started/index.md
  - Infrastructure: infrastructure/index.md
  - Kubernetes: kubernetes/index.md
  - Observability: o11y/index.md
  - Technical Solutions: technical_solutions/index.md
  - Toolchain: toolchain/index.md
  - Tutorials: tutorials/index.md
repo_url: https://github.com/khngu/khngu.github.io
edit_uri: edit/main/website/content/docs/developer_manual
plugins:
  - techdocs-core
  - search
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
theme:
  name: material
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
