site_name: 'Onboarding'
site_description: 'Developer Onboarding Guide'
docs_dir: docs
nav:
  - Overview: developer_manual/_index.md
  - Getting Started: 
    - Overview: developer_manual/getting_started/_index.md
    - Manual Setup: developer_manual/getting_started/manual_setup.md
    - Naming Conventions: developer_manual/getting_started/repo_naming_conventions.md
    - Request Access: developer_manual/getting_started/request_access.md
  - Infrastructure:
    - Overview: developer_manual/infrastructure/_index.md
    - AWS Authentication and Authorization: developer_manual/infrastructure/aws_authn_authz/index.md
    - Infrastructure Development: developer_manual/infrastructure/infrastructure_development.md
    - Dirty States: developer_manual/infrastructure/dirty_states/index.md
    - PCS States: developer_manual/infrastructure/pcs_scheduler.md
  - Kubernetes: 
    - Overview: developer_manual/kubernetes/_index.md
    - Getting Started: developer_manual/kubernetes/getting_started.md
    - CET vs. Legacy: developer_manual/kubernetes/cet_vs_legacy.md
    - Downscaling: developer_manual/kubernetes/downscaling.md
    - External Auth: developer_manual/kubernetes/external-authentication.md
    - Helm Charts: developer_manual/kubernetes/helm_render.md
    - Helm Charts Compliance: developer_manual/kubernetes/helm-chart-compliance.md
    - Karpenter Provisioners: developer_manual/kubernetes/karpenter_provisioners.md
    - Pods in host network: developer_manual/kubernetes/host-network.md
    - Portal: developer_manual/kubernetes/portal/index.md
    - Updating: developer_manual/kubernetes/updating.md
    - Updating Istio: developer_manual/kubernetes/updating-istio.md
    - Known Issues: developer_manual/kubernetes/known_issues/_index.md
  - Observability: 
    - Overview: developer_manual/o11y/_index.md
    - ArgoCD Alerts: developer_manual/o11y/argocd-alerts.md
    - End-To-End (E2E):
      - Introduction: developer_manual/o11y/e2e/_index.md
      - Onboarding: developer_manual/o11y/e2e/onboarding.md
      - Architecture: developer_manual/o11y/e2e/architecture/index.md
      - Designing OTelCols For E2E: developer_manual/o11y/e2e/otelcol-e2e-design.md
      - How To Content: developer_manual/o11y/e2e/how-to-content.md
      - Using OTelCol Filters: developer_manual/o11y/e2e/otelcol-e2e-filters.md
    - Non-EKS workloads: developer_manual/o11y/non-eks.md
  - Toolchain:
    - Overview: developer_manual/toolchain/_index.md
    - Toolchain Guide: developer_manual/toolchain/toolchain_guide.md
    - AWS Workspaces: developer_manual/toolchain/aws-workspaces.md
    - Lifehacks: developer_manual/toolchain/lifehacks/index.md
  - Technical Solutions:
    - Overview: developer_manual/technical_solutions/_index.md
    - Docker Builds: developer_manual/technical_solutions/docker_builds/index.md
    - OCI Helm Chart Builds: developer_manual/technical_solutions/oci_helm_charts_build/index.md
    - Packer Builds: developer_manual/technical_solutions/packer_builds/index.md
    - Privatelinks: developer_manual/technical_solutions/privatelink_guide/index.md
    - Public LB with GitHub Auth: developer_manual/technical_solutions/public_load_balancer_guide/index.md
    - Public LB with Azure Auth: developer_manual/technical_solutions/public_load_balancer_oidc_guide/index.md
    - Cribl/TTWOS Integration: developer_manual/technical_solutions/cribl_integration/index.md
  - Tutorials:
    - Overview: developer_manual/tutorials/_index.md
    - How to migrate external secrets operator: developer_manual/tutorials/how_to_change_external_secrets_operator.md
    - How to testing Terraform: developer_manual/tutorials/how_to_terragrunt_local_apply.md
    - How to Terraform module: developer_manual/tutorials/how_to_create_a_terraform_module/index.md
    - How to maintain a Terraform Project Repository: developer_manual/tutorials/how_to_maintain_a_terraform_project.md
    - How to PR: developer_manual/tutorials/how_to_pr/index.md
    - How to SemVer: developer_manual/tutorials/how_to_semver.md
    - How to AWS IDP Transition: developer_manual/tutorials/how_to_idps_transition.md
    - How to CAWS and PAM: developer_manual/tutorials/how_to_config_caws_to_use_pam/index.md
    - How to Git: developer_manual/tutorials/how_to_git/index.md
repo_url: https://github.com/khngu/khngu.github.io
edit_uri: edit/main/docs
plugins:
  - techdocs-core
  - search
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
theme:
  name: material
#  palette:
    #- scheme: default
    #  primary: red
    #  accent: red
    #- scheme: slate
    #  primary: indigo
    #  accent: indigo
#  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
