asite_name: 'My Documentation'
site_description: 'My GitHub Pages Documentation'
docs_dir: 'website/content/docs/developer_manual'
nav:
  - Home: _index.md
  - Getting Started: getting_started/
  - Infrastructure: infrastructure/
  - Kubernetes: kubernetes/
  - Observability: o11y/
  - Technical Solutions: technical_solutions/
  - Toolchain: toolchain/
  - Tutorials: tutorials/
  - .DS_Store: .DS_Store
repo_url: https://github.com/khngu/khngu.github.io
edit_uri: edit/main/website/content/docs/developer_manual
plugins:
  - techdocs-core
  - search
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
theme:
  name: material
  palette:
    #- scheme: default
    #  primary: red
    #  accent: red
    #- scheme: slate
    #  primary: indigo
    #  accent: indigo
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
