site_name: 'My Documentation'
site_description: 'My GitHub Pages Documentation'
docs_dir: 'website/content/docs/developer_manual'
nav:
  - Home: website/content/docs/developer_manual/_index.md
  - Getting Started: website/content/docs/developer_manual/getting_started/_index.md
  - Infrastructure: website/content/docs/developer_manual/infrastructure/_index.md
  - Kubernetes: website/content/docs/developer_manual/kubernetes/_index.md
  - Observability: website/content/docs/developer_manual/o11y/_index.md
  - Technical Solutions: website/content/docs/developer_manual/technical_solutions/_index.md
  - Toolchain: website/content/docs/developer_manual/toolchain/_index.md
  - Tutorials: website/content/docs/developer_manual/tutorials/_index.md
repo_url: https://github.com/khngu/khngu.github.io
edit_uri: main/website/content/docs/developer_manual
plugins:
  - techdocs-core
  - search
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
theme:
  name: material
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
