site_name: 'My Documentation'
site_description: 'My GitHub Pages Documentation'
docs_dir: docs
nav:
  - Home: index.md
  - Onboarding: onboarding.md
  - Team: team.md
  - Tools: tools.md
  - Getting Started 1: getting-started.md
  - Getting Started 2: test/getting-started.md
  - Test: test/test2/_index.md
  - Overview: developer_manual/_index.md
  - Getting Started 3: developer_manual/getting_started/_index.md
repo_url: https://github.com/khngu/khngu.github.io/tree/main/docs
edit_uri: edit/main/docs
plugins:
  - techdocs-core
  - search
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - extra.css
extra_javascript:
  - extra.js
theme:
  name: material
  palette:
    #- scheme: default
    #  primary: red
    #  accent: red
    #- scheme: slate
    #  primary: indigo
    #  accent: indigo
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
