site_name: 'My Documentation'
site_description: 'My GitHub Pages Documentation'
docs_dir: docs
nav:
  - Overview: developer_manual/_index.md
  - Getting Started: 
    - Overview: developer_manual/getting_started/_index.md
    - Manual Setup: developer_manual/getting_started/manual_setup.md
    - Naming Conventions: developer_manual/getting_started/repo_naming_conventions.md
    - Request Access: developer_manual/getting_started/request_access.md
  - Infrastructure:
    - Overview: developer_manual/infrastructure/_index.md
    - AWS Authentication and Authorization: developer_manual/infrastructure/aws_authn_authz/index.md
    - Infrastructure Development: developer_manual/infrastructure/infrastructure_development.md
    - Dirty States: developer_manual/infrastructure/dirty_states/index.md
    - PCS States: developer_manual/infrastructure/pcs_scheduler.md
  - Kubernetes: 
    - Overview: developer_manual/kubernetes/_index.md
    - Getting Started: developer_manual/kubernetes/getting_started.md
    - CET vs. Legacy: developer_manual/kubernetes/cet_vs_legacy.md
    - Downscaling: developer_manual/kubernetes/downscaling.md
    - External Auth: developer_manual/kubernetes/external-authentication.md
    - Helm Charts: developer_manual/kubernetes/helm_render.md
    - Helm Charts Compliance: developer_manual/kubernetes/helm-chart-compliance.md
    - Karpenter Provisioners: developer_manual/kubernetes/karpenter_provisioners.md
    - Pods in host network: developer_manual/kubernetes/host-network.md
    - Portal: developer_manual/kubernetes/portal/index.md
    - Updating: developer_manual/kubernetes/updating.md
    - Updating Istio: developer_manual/kubernetes/updating-istio.md
    - Known Issues: developer_manual/kubernetes/known_issues/_index.md
  - Observability: 
    - Overview: developer_manual/o11y/_index.md
    - ArgoCD Alerts: developer_manual/o11y/argocd-alerts.md
    - End-To-End (E2E):
      - Introduction: developer_manual/o11y/e2e/_index.md
      - Onboarding: developer_manual/o11y/e2e/onboarding.md
      - Architecture: developer_manual/o11y/e2e/architecture/index.md
      - Designing OTelCols For E2E: developer_manual/o11y/e2e/otelcol-e2e-design.md
      - How To Content: developer_manual/o11y/e2e/how-to-content.md
      - Using OTelCol Filters: developer_manual/o11y/e2e/otelcol-e2e-filters.md
    - Non-EKS workloads: developer_manual/o11y/non-eks.md
  - Toolchain:
    - Overview: developer_manual/toolchain/_index.md
    - Toolchain Guide: developer_manual/toolchain/toolchain_guide.md
    - AWS Workspaces: developer_manual/toolchain/aws-workspaces.md
    - Lifehacks: developer_manual/toolchain/lifehacks/index.md
  #- Technical Solutions:
  #  - Overview:
  #  - Docker Builds:
  #  - OCI Helm Chart Builds:
  #  - Packer Builds:
  #  - Privatelinks:
  #  - Public LB with GitHub Auth:
  #  - Public LB with Azure Auth:
  #  - Cribl/TTWOS Integration:
repo_url: https://github.com/khngu/khngu.github.io/tree/main/docs
edit_uri: edit/main/docs
plugins:
  - techdocs-core
  - search
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - extra.css
extra_javascript:
  - extra.js
theme:
  name: material
  palette:
    #- scheme: default
    #  primary: red
    #  accent: red
    #- scheme: slate
    #  primary: indigo
    #  accent: indigo
  favicon: assets/favicon.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
